name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install Dependencies
        run: npm ci
        
      - name: Optimize CSS and JavaScript
        run: |
          # Minify the CSS
          npx clean-css-cli@5 index.html -o temp.html
          mv temp.html index.html
      
      - name: Compress JSON Files
        run: |
          # Create compressed versions of JSON files
          node compress-json.js
          
          # Replace data directory with optimized files for deployment
          rm -rf data
          mv data-compressed data
      
      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          clean: true 