name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Install Dependencies
        run: npm ci
        
      - name: Optimize CSS and JavaScript
        run: |
          # Minify the CSS
          npx clean-css-cli@5 index.html -o temp.html
          mv temp.html index.html
      
      - name: Compress JSON Files
        run: |
          # Create compressed versions of JSON files
          node compress-json.js
          
          # Replace data directory with optimized files for deployment
          rm -rf data
          mv data-compressed data
      
      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: . 